language: node_js
node_js: --lts # LTS
cache: yarn
before_script:
  - yarn lint
script:
  - yarn test
  - yarn e2e
after_success:
  - yarn build # Prevent before_deploy not being tested in PRs
  - test "$TRAVIS_PULL_REQUEST" = false || yarn lighthouse # Run Lighthouse on PR only
  - codecov
deploy:
  provider: script
  script: yarn deploy # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID must be set
  skip_cleanup: true
  on:
    branch: master
