language: node_js
node_js: --lts # LTS
cache: yarn
before_script:
  - yarn lint
script:
  - yarn test
  - yarn e2e
after_success:
  - yarn build # Prevent before_deploy not being tested in PRs
  - yarn lighthouse
  - codecov
before_deploy:
  - echo "$CNAME" > dist/CNAME
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: dist
  skip_cleanup: true
  keep-history: true
  on:
    branch: master
